# Generated by Django 3.2.23 on 2024-05-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_v2', '0019_trainer_trainerteammember_trainerteammembermove'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrophyGardenSpecialEncounters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_level', models.IntegerField()),
                ('max_level', models.IntegerField()),
                ('pokemon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trophygardenspecialencounters', to='pokemon_v2.pokemon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
